version: "3.8"
services:
  server1-app:
    build: ./server1-app
    container_name: server1-app
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
      - otel-collector
    environment:
      - PORT=3000

  server2-app:
    build: ./server2-app
    container_name: server2-app
    ports:
      - "3001:3000"
    depends_on:
      - elasticsearch
      - otel-collector
    environment:
      - PORT=3000

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY="abcdefghijklmnopqrstuvwxzy123456"
      - XPACK_REPORTING_ENCRYPTIONKEY="abcdefghijklmnopqrstuvwxzy123456"
      - XPACK_SECURITY_ENCRYPTIONKEY="abcdefghijklmnopqrstuvwxzy123456"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - elasticsearch
    environment:
      - DEPLOYMENT_ENV=production   # set the DEPLOYMENT_ENV variable
